tasks:
  - command: |
      npx -y cowsay "Preview browser should open by itself, without clicking inside VScode's Terminal panel"
      npx -y serve &
      gp await-port 3000
      sleep 1
      gp preview $(gp url 3000)

ports:
  - port: 3000
    onOpen: ignore
